workflows:
  ios_debug:
    name: Lejna iOS Debug (no codesign)
    max_build_duration: 60

    environment:
      vars:
        FLUTTER_VERSION: "3.24.3"
      xcode: 15.4
      cocoapods: default

    cache:
      cache_paths:
        - ~/.flutter-sdk
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Install Flutter via shallow git (cached)
        script: |
          #!/bin/sh
          set -e
          SDK_ROOT="$HOME/.flutter-sdk"
          SDK_DIR="$SDK_ROOT/$FLUTTER_VERSION"
          REPO_URL="https://github.com/flutter/flutter"
          mkdir -p "$SDK_ROOT"
          if [ ! -x "$SDK_DIR/bin/flutter" ]; then
            rm -rf "$SDK_DIR.tmp"
            i=1
            while [ $i -le 3 ]; do
              echo "Clone attempt $i/3…"
              if git clone --depth 1 --branch "$FLUTTER_VERSION" "$REPO_URL" "$SDK_DIR.tmp"; then
                mv "$SDK_DIR.tmp" "$SDK_DIR"
                break
              fi
              [ $i -eq 3 ] && { echo "Failed to clone Flutter after 3 attempts"; exit 2; }
              sleep 10; i=$((i+1))
            done
          else
            echo "Flutter $FLUTTER_VERSION already cached at $SDK_DIR"
          fi
          export PATH="$SDK_DIR/bin:$PATH"
          flutter --version
          flutter config --no-analytics
          flutter precache --ios

      - name: Pub get
        script: |
          #!/bin/sh
          set -e
          export PATH="$HOME/.flutter-sdk/$FLUTTER_VERSION/bin:$PATH"
          flutter pub get

      - name: Podfile sanitize + robust pod install (POSIX)
        script: |
          #!/bin/sh
          set -e
          if ! grep -q "^source 'https://cdn.cocoapods.org/'" ios/Podfile; then
            printf "source 'https://cdn.cocoapods.org/'\n%s" "$(cat ios/Podfile)" > ios/Podfile
          fi
          sed -i.bak 's/[‘’]/'\''/g; s/[“”]/"/g; s/[–—]/-/g; s/…/.../g' ios/Podfile || true
          rm -f ios/Podfile.bak
          cd ios
          pod repo update
          pod deintegrate || true
          rm -rf Pods Podfile.lock
          attempts=3; delay=10; i=1
          while [ "$i" -le "$attempts" ]; do
            echo "pod install attempt $i/$attempts…"
            if pod install --repo-update; then
              echo "pod install succeeded on attempt $i"; break
            fi
            if [ "$i" -eq "$attempts" ]; then
              echo "pod install failed after $attempts attempts"; exit 2
            fi
            echo "Retrying in ${delay}s…"; sleep "$delay"; i=$(( i + 1 ))
          done
          cd ..

      - name: Build iOS debug (no codesign)
        script: |
          #!/bin/sh
          set -e
          export PATH="$HOME/.flutter-sdk/$FLUTTER_VERSION/bin:$PATH"
          flutter build ios --debug --no-codesign -v

  ios_testflight:
    name: Lejna iOS Release → TestFlight
    max_build_duration: 90

    integrations:
      app_store_connect: Lejna_ASC   # Use your connected Apple Developer Portal integration

    environment:
      vars:
        FLUTTER_VERSION: "3.24.3"
        BUNDLE_ID: "com.lejna.app"
        IOS_DISPLAY_NAME: "Lejna"
        IOS_VERSION_NAME: "1.0.0"
      groups:
        - asc_credentials            # ok to keep; not strictly required when using integration
      xcode: 15.4
      cocoapods: default

    cache:
      cache_paths:
        - ~/.flutter-sdk
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Install Flutter via shallow git (cached)
        script: |
          #!/bin/sh
          set -e
          SDK_ROOT="$HOME/.flutter-sdk"
          SDK_DIR="$SDK_ROOT/$FLUTTER_VERSION"
          REPO_URL="https://github.com/flutter/flutter"
          mkdir -p "$SDK_ROOT"
          if [ ! -x "$SDK_DIR/bin/flutter" ]; then
            rm -rf "$SDK_DIR.tmp"
            i=1; while [ $i -le 3 ]; do
              git clone --depth 1 --branch "$FLUTTER_VERSION" "$REPO_URL" "$SDK_DIR.tmp" && break
              [ $i -eq 3 ] && { echo "Flutter clone failed"; exit 2; }
              sleep 10; i=$((i+1))
            done
            mv "$SDK_DIR.tmp" "$SDK_DIR"
          fi
          export PATH="$SDK_DIR/bin:$PATH"
          flutter --version
          flutter config --no-analytics
          flutter precache --ios

      - name: Pub get
        script: |
          #!/bin/sh
          set -e
          export PATH="$HOME/.flutter-sdk/$FLUTTER_VERSION/bin:$PATH"
          flutter pub get

      - name: Podfile sanitize + robust pod install
        script: |
          #!/bin/sh
          set -e
          if ! grep -q "^source 'https://cdn.cocoapods.org/'" ios/Podfile; then
            printf "source 'https://cdn.cocoapods.org/'\n%s" "$(cat ios/Podfile)" > ios/Podfile
          fi
          sed -i.bak 's/[‘’]/'\''/g; s/[“”]/"/g; s/[–—]/-/g; s/…/.../g' ios/Podfile || true
          rm -f ios/Podfile.bak
          cd ios
          pod repo update
          pod deintegrate || true
          rm -rf Pods Podfile.lock
          i=1; while [ $i -le 3 ]; do
            pod install --repo-update && break
            [ $i -eq 3 ] && { echo "pod install failed"; exit 2; }
            sleep 10; i=$((i+1))
          done
          cd ..

      - name: Fetch signing files and set Xcode profiles (App Store) via Integration
        script: |
          #!/bin/sh
          set -e
          # Credentials are injected from the connected integration (Lejna_ASC)
          app-store-connect fetch-signing-files "${BUNDLE_ID}" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles --bundle-id "${BUNDLE_ID}"

      - name: Set bundle id, name, versions and build IPA (Release)
        script: |
          #!/bin/sh
          set -e
          export PATH="$HOME/.flutter-sdk/$FLUTTER_VERSION/bin:$PATH"
          sed -i '' "s/com\.example\.lejnaApp/${BUNDLE_ID}/g" ios/Runner.xcodeproj/project.pbxproj
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName ${IOS_DISPLAY_NAME}" ios/Runner/Info.plist 2>/dev/null || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string ${IOS_DISPLAY_NAME}" ios/Runner/Info.plist
          BUILD_NUM="${BUILD_NUMBER:-1}"
          flutter build ipa --release --build-name="${IOS_VERSION_NAME}" --build-number="${BUILD_NUM}"

    artifacts:
      - build/ios/**/*.ipa
      - build/ios/archive/**/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testing
