name: lejna
description: A building committee management app for residents and building administrators in Lebanon.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.3
  go_router: ^6.5.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.3
  cloud_functions: ^4.3.4
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^17.2.1
  firebase_crashlytics: ^3.3.4
  firebase_analytics: ^10.4.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  pdf: ^3.8.1
  printing: ^5.11.1
  image_picker: ^1.0.5
  file_picker: ^10.3.3
  share_plus: ^7.0.2
  qr_flutter: ^4.1.0
  csv: ^5.0.2
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  uuid: ^3.0.7
  sentry_flutter: ^8.8.0
  flutter_markdown: ^0.6.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  # Specify where the localization files live
  # When `flutter gen-l10n` runs, it will generate localization delegates.
  generate: true
  assets:
    - assets/images/
    - assets/icons/android/
    - assets/icons/ios/
    - assets/icons/vector/
    - assets/icons/play/
    - assets/legal/
